image: registry.gitlab.com/satoshilabs/trezor/trezor-firmware/trezor-firmware-env.nix

variables:
  SDL_VIDEODRIVER: "dummy"
  XDG_RUNTIME_DIR: "/var/tmp"

# Legacy

legacy fw regular build:
  stage: build
  needs: []
  variables:
    MEMORY_PROTECT: "0"
  script:
    - nix-shell --run "arm-none-eabi-gcc --version"
    - nix-shell --run "poetry run legacy/script/cibuild"
    - nix-shell --run "poetry run make -C legacy/demo"
    - mv legacy/firmware/trezor.bin trezor-fw-regular-$LEGACY_VERSION-$CI_COMMIT_SHORT_SHA.bin
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - trezor-fw-regular-*.*.*-$CI_COMMIT_SHORT_SHA.bin
    expire_in: 1 week
